// <auto-generated />
using System;
using CertMonitor.Server.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace CertMonitor.Server.Data.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260322100215_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("CertMonitor.Server.Models.Domain.Agent", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("AgentVersion")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<DateTime>("LastScanAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("WorkstationId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("WorkstationId")
                        .IsUnique();

                    b.ToTable("Agents", (string)null);
                });

            modelBuilder.Entity("CertMonitor.Server.Models.Domain.Certificate", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Algorithm")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<DateTime>("FirstSeenAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Issuer")
                        .IsRequired()
                        .HasMaxLength(1024)
                        .HasColumnType("character varying(1024)");

                    b.Property<DateTime>("LastSeenAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("SerialNumber")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("SourceType")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("Subject")
                        .IsRequired()
                        .HasMaxLength(1024)
                        .HasColumnType("character varying(1024)");

                    b.Property<string>("Thumbprint")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<int?>("TokenDeviceId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("ValidFromUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("ValidToUtc")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("Thumbprint")
                        .IsUnique()
                        .HasFilter("\"Thumbprint\" IS NOT NULL AND \"Thumbprint\" <> ''");

                    b.HasIndex("TokenDeviceId");

                    b.HasIndex("Issuer", "SerialNumber")
                        .IsUnique()
                        .HasFilter("\"Thumbprint\" IS NULL OR \"Thumbprint\" = ''");

                    b.ToTable("Certificates", (string)null);
                });

            modelBuilder.Entity("CertMonitor.Server.Models.Domain.CertificateDetection", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("CertificateId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("DetectedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("ScanSessionId")
                        .HasColumnType("integer");

                    b.Property<int?>("TokenDeviceId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("CertificateId");

                    b.HasIndex("TokenDeviceId");

                    b.HasIndex("ScanSessionId", "CertificateId", "TokenDeviceId")
                        .IsUnique();

                    b.ToTable("CertificateDetections", (string)null);
                });

            modelBuilder.Entity("CertMonitor.Server.Models.Domain.ScanSession", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("AgentId")
                        .HasColumnType("integer");

                    b.Property<int>("CertificatesFoundCount")
                        .HasColumnType("integer");

                    b.Property<DateTime>("FinishedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("RawPayloadJson")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("SessionUid")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<DateTime>("StartedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<int>("TokensFoundCount")
                        .HasColumnType("integer");

                    b.Property<int>("WorkstationId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("AgentId");

                    b.HasIndex("SessionUid")
                        .IsUnique();

                    b.HasIndex("WorkstationId");

                    b.ToTable("ScanSessions", (string)null);
                });

            modelBuilder.Entity("CertMonitor.Server.Models.Domain.TokenDevice", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("FirstSeenAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("LastSeenAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Manufacturer")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("Model")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("Pkcs11SlotId")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("SerialNumber")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("TokenType")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<int>("WorkstationId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("SerialNumber")
                        .IsUnique();

                    b.HasIndex("WorkstationId");

                    b.ToTable("TokenDevices", (string)null);
                });

            modelBuilder.Entity("CertMonitor.Server.Models.Domain.Workstation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("DeviceUid")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<DateTime>("FirstSeenAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Hostname")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<DateTime>("LastSeenAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("DeviceUid")
                        .IsUnique();

                    b.ToTable("Workstations", (string)null);
                });

            modelBuilder.Entity("CertMonitor.Server.Models.Domain.Agent", b =>
                {
                    b.HasOne("CertMonitor.Server.Models.Domain.Workstation", "Workstation")
                        .WithOne("Agent")
                        .HasForeignKey("CertMonitor.Server.Models.Domain.Agent", "WorkstationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Workstation");
                });

            modelBuilder.Entity("CertMonitor.Server.Models.Domain.Certificate", b =>
                {
                    b.HasOne("CertMonitor.Server.Models.Domain.TokenDevice", "TokenDevice")
                        .WithMany("Certificates")
                        .HasForeignKey("TokenDeviceId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("TokenDevice");
                });

            modelBuilder.Entity("CertMonitor.Server.Models.Domain.CertificateDetection", b =>
                {
                    b.HasOne("CertMonitor.Server.Models.Domain.Certificate", "Certificate")
                        .WithMany("CertificateDetections")
                        .HasForeignKey("CertificateId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("CertMonitor.Server.Models.Domain.ScanSession", "ScanSession")
                        .WithMany("CertificateDetections")
                        .HasForeignKey("ScanSessionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CertMonitor.Server.Models.Domain.TokenDevice", "TokenDevice")
                        .WithMany("CertificateDetections")
                        .HasForeignKey("TokenDeviceId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Certificate");

                    b.Navigation("ScanSession");

                    b.Navigation("TokenDevice");
                });

            modelBuilder.Entity("CertMonitor.Server.Models.Domain.ScanSession", b =>
                {
                    b.HasOne("CertMonitor.Server.Models.Domain.Agent", "Agent")
                        .WithMany("ScanSessions")
                        .HasForeignKey("AgentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("CertMonitor.Server.Models.Domain.Workstation", "Workstation")
                        .WithMany("ScanSessions")
                        .HasForeignKey("WorkstationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Agent");

                    b.Navigation("Workstation");
                });

            modelBuilder.Entity("CertMonitor.Server.Models.Domain.TokenDevice", b =>
                {
                    b.HasOne("CertMonitor.Server.Models.Domain.Workstation", "Workstation")
                        .WithMany("TokenDevices")
                        .HasForeignKey("WorkstationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Workstation");
                });

            modelBuilder.Entity("CertMonitor.Server.Models.Domain.Agent", b =>
                {
                    b.Navigation("ScanSessions");
                });

            modelBuilder.Entity("CertMonitor.Server.Models.Domain.Certificate", b =>
                {
                    b.Navigation("CertificateDetections");
                });

            modelBuilder.Entity("CertMonitor.Server.Models.Domain.ScanSession", b =>
                {
                    b.Navigation("CertificateDetections");
                });

            modelBuilder.Entity("CertMonitor.Server.Models.Domain.TokenDevice", b =>
                {
                    b.Navigation("CertificateDetections");

                    b.Navigation("Certificates");
                });

            modelBuilder.Entity("CertMonitor.Server.Models.Domain.Workstation", b =>
                {
                    b.Navigation("Agent");

                    b.Navigation("ScanSessions");

                    b.Navigation("TokenDevices");
                });
#pragma warning restore 612, 618
        }
    }
}
