CREATE TABLE IF NOT EXISTS "__EFMigrationsHistory" (
    "MigrationId" character varying(150) NOT NULL,
    "ProductVersion" character varying(32) NOT NULL,
    CONSTRAINT "PK___EFMigrationsHistory" PRIMARY KEY ("MigrationId")
);

START TRANSACTION;

CREATE TABLE "Workstations" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "DeviceUid" character varying(256) NOT NULL,
    "Hostname" character varying(256) NOT NULL,
    "FirstSeenAtUtc" timestamp with time zone NOT NULL,
    "LastSeenAtUtc" timestamp with time zone NOT NULL,
    CONSTRAINT "PK_Workstations" PRIMARY KEY ("Id")
);

CREATE TABLE "Agents" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "WorkstationId" integer NOT NULL,
    "AgentVersion" character varying(64) NOT NULL,
    "LastScanAtUtc" timestamp with time zone NOT NULL,
    CONSTRAINT "PK_Agents" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_Agents_Workstations_WorkstationId" FOREIGN KEY ("WorkstationId") REFERENCES "Workstations" ("Id") ON DELETE RESTRICT
);

CREATE TABLE "TokenDevices" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "SerialNumber" character varying(256) NOT NULL,
    "TokenType" character varying(256) NOT NULL,
    "Model" character varying(256) NOT NULL,
    "Manufacturer" character varying(256) NOT NULL,
    "Pkcs11SlotId" character varying(128) NOT NULL,
    "WorkstationId" integer NOT NULL,
    "FirstSeenAtUtc" timestamp with time zone NOT NULL,
    "LastSeenAtUtc" timestamp with time zone NOT NULL,
    CONSTRAINT "PK_TokenDevices" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_TokenDevices_Workstations_WorkstationId" FOREIGN KEY ("WorkstationId") REFERENCES "Workstations" ("Id") ON DELETE RESTRICT
);

CREATE TABLE "ScanSessions" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "SessionUid" character varying(256) NOT NULL,
    "WorkstationId" integer NOT NULL,
    "AgentId" integer NOT NULL,
    "StartedAtUtc" timestamp with time zone NOT NULL,
    "FinishedAtUtc" timestamp with time zone NOT NULL,
    "Status" character varying(64) NOT NULL,
    "TokensFoundCount" integer NOT NULL,
    "CertificatesFoundCount" integer NOT NULL,
    "RawPayloadJson" text NOT NULL,
    CONSTRAINT "PK_ScanSessions" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_ScanSessions_Agents_AgentId" FOREIGN KEY ("AgentId") REFERENCES "Agents" ("Id") ON DELETE RESTRICT,
    CONSTRAINT "FK_ScanSessions_Workstations_WorkstationId" FOREIGN KEY ("WorkstationId") REFERENCES "Workstations" ("Id") ON DELETE RESTRICT
);

CREATE TABLE "Certificates" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "Thumbprint" character varying(256),
    "Issuer" character varying(1024) NOT NULL,
    "Subject" character varying(1024) NOT NULL,
    "SerialNumber" character varying(256) NOT NULL,
    "ValidFromUtc" timestamp with time zone NOT NULL,
    "ValidToUtc" timestamp with time zone NOT NULL,
    "Algorithm" character varying(256) NOT NULL,
    "SourceType" character varying(64) NOT NULL,
    "TokenDeviceId" integer,
    "FirstSeenAtUtc" timestamp with time zone NOT NULL,
    "LastSeenAtUtc" timestamp with time zone NOT NULL,
    CONSTRAINT "PK_Certificates" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_Certificates_TokenDevices_TokenDeviceId" FOREIGN KEY ("TokenDeviceId") REFERENCES "TokenDevices" ("Id") ON DELETE RESTRICT
);

CREATE TABLE "CertificateDetections" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "ScanSessionId" integer NOT NULL,
    "CertificateId" integer NOT NULL,
    "TokenDeviceId" integer,
    "DetectedAtUtc" timestamp with time zone NOT NULL,
    CONSTRAINT "PK_CertificateDetections" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_CertificateDetections_Certificates_CertificateId" FOREIGN KEY ("CertificateId") REFERENCES "Certificates" ("Id") ON DELETE RESTRICT,
    CONSTRAINT "FK_CertificateDetections_ScanSessions_ScanSessionId" FOREIGN KEY ("ScanSessionId") REFERENCES "ScanSessions" ("Id") ON DELETE CASCADE,
    CONSTRAINT "FK_CertificateDetections_TokenDevices_TokenDeviceId" FOREIGN KEY ("TokenDeviceId") REFERENCES "TokenDevices" ("Id") ON DELETE RESTRICT
);

CREATE UNIQUE INDEX "IX_Agents_WorkstationId" ON "Agents" ("WorkstationId");

CREATE INDEX "IX_CertificateDetections_CertificateId" ON "CertificateDetections" ("CertificateId");

CREATE UNIQUE INDEX "IX_CertificateDetections_ScanSessionId_CertificateId_TokenDevi~" ON "CertificateDetections" ("ScanSessionId", "CertificateId", "TokenDeviceId");

CREATE INDEX "IX_CertificateDetections_TokenDeviceId" ON "CertificateDetections" ("TokenDeviceId");

CREATE UNIQUE INDEX "IX_Certificates_Issuer_SerialNumber" ON "Certificates" ("Issuer", "SerialNumber") WHERE "Thumbprint" IS NULL OR "Thumbprint" = '';

CREATE UNIQUE INDEX "IX_Certificates_Thumbprint" ON "Certificates" ("Thumbprint") WHERE "Thumbprint" IS NOT NULL AND "Thumbprint" <> '';

CREATE INDEX "IX_Certificates_TokenDeviceId" ON "Certificates" ("TokenDeviceId");

CREATE INDEX "IX_ScanSessions_AgentId" ON "ScanSessions" ("AgentId");

CREATE UNIQUE INDEX "IX_ScanSessions_SessionUid" ON "ScanSessions" ("SessionUid");

CREATE INDEX "IX_ScanSessions_WorkstationId" ON "ScanSessions" ("WorkstationId");

CREATE UNIQUE INDEX "IX_TokenDevices_SerialNumber" ON "TokenDevices" ("SerialNumber");

CREATE INDEX "IX_TokenDevices_WorkstationId" ON "TokenDevices" ("WorkstationId");

CREATE UNIQUE INDEX "IX_Workstations_DeviceUid" ON "Workstations" ("DeviceUid");

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20260322100215_InitialCreate', '8.0.0');

COMMIT;

